export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL"

export const GET_APRODUCT_REQUEST="GET_APRODUCT_REQUEST"
export const GET_APRODUCT_SUCCESS="GET_APRODUCT_SUCCESS"
export const GET_APRODUCT_FAIL="GET_APRODUCT_FAIL"
